platform :ios, '8.0'

abstract_target 'defaults' do
pod 'AFNetworking', '~> 2.3'
pod 'SDWebImage', '~> 3.7'
pod 'JSONModel', '~> 1.3.0'
pod 'Mixpanel', '~> 2.9'
pod 'SlackTextViewController'
pod 'LoremIpsum', '~> 1.0'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Google/Analytics'
pod 'Fabric'
pod 'Crashlytics'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Google/SignIn'
pod 'SVProgressHUD'
pod 'AWSCore'
pod 'AWSS3'
pod 'RSKImageCropper'
pod 'MBProgressHUD', '0.8'
pod 'GPUImage', '~> 0.1.6'
pod 'AFOAuth2Manager'
pod "youtube-ios-player-helper", "~> 0.1.4"
pod 'Branch'
pod 'ionicons'
pod 'HTHorizontalSelectionList', '~> 0.7.4'
pod 'FontAwesome'
pod 'FCAlertView'
pod 'IQKeyboardManager'

target 'EventChat'
target 'P90x'
target 'EdgeTVChat'
target 'CoachellaChat'

end
